//
//  RoutineManager.swift
//  iAlly
//
//  Created on 9/12/2025.
//

import Foundation
import SwiftData
import UIKit

@MainActor
class RoutineManager {
    static let shared = RoutineManager()
    
    private init() {}
    
    /// Generate tasks from all active routines
    func generateTasksFromRoutines(context: ModelContext) async {
        let descriptor = FetchDescriptor<Routine>(
            predicate: #Predicate { $0.isActive }
        )
        
        guard let routines = try? context.fetch(descriptor) else { return }
        
        for routine in routines {
            await generateTasksForRoutine(routine, context: context)
        }
        
        try? context.save()
    }
    
    /// Generate tasks for a specific routine
    func generateTasksForRoutine(_ routine: Routine, context: ModelContext) async {
        let calendar = Calendar.current
        let today = calendar.startOfDay(for: Date())
        let daysAhead = routine.autoGenerateDays
        
        // Get last generated date, default to yesterday if never generated
        let lastGenerated = routine.lastGeneratedDate ?? calendar.date(byAdding: .day, value: -1, to: today)!
        
        // Calculate generation end date: use routine.endDate if set, otherwise autoGenerateDays
        let generationEndDate: Date
        if let endDate = routine.endDate {
            generationEndDate = min(endDate, calendar.date(byAdding: .day, value: daysAhead, to: today)!)
        } else {
            generationEndDate = calendar.date(byAdding: .day, value: daysAhead, to: today)!
        }
        
        // Generate tasks from last generated date up to generation end date
        var datesToGenerate: [Date] = []
        
        switch routine.frequency {
        case .daily:
            // Generate for each day up to end date
            for dayOffset in 0..<daysAhead {
                if let targetDate = calendar.date(byAdding: .day, value: dayOffset, to: today),
                   targetDate > lastGenerated,
                   targetDate <= generationEndDate {
                    datesToGenerate.append(targetDate)
                }
            }
            
        case .weekly:
            // Generate for specified days of week up to end date
            guard let activeDays = routine.activeDays, !activeDays.isEmpty else { return }
            
            for dayOffset in 0..<daysAhead {
                if let targetDate = calendar.date(byAdding: .day, value: dayOffset, to: today),
                   targetDate > lastGenerated,
                   targetDate <= generationEndDate {
                    let weekday = calendar.component(.weekday, from: targetDate)
                    // activeDays uses Apple Calendar convention: 1=Sun, 2=Mon, ..., 7=Sat
                    if activeDays.contains(weekday) {
                        datesToGenerate.append(targetDate)
                    }
                }
            }

        case .monthly:
            // Generate for specified day of month
            guard let activeDays = routine.activeDays, let dayOfMonth = activeDays.first else { return }
            
            let currentMonth = calendar.component(.month, from: today)
            let currentYear = calendar.component(.year, from: today)
            
            // Check current and next month
            for monthOffset in 0...1 {
                var components = DateComponents()
                components.year = currentYear
                components.month = currentMonth + monthOffset
                components.day = dayOfMonth
                
                if let targetDate = calendar.date(from: components),
                   targetDate >= today,
                   targetDate > lastGenerated,
                   targetDate <= generationEndDate {
                    datesToGenerate.append(targetDate)
                }
            }
            
        case .custom:
            // Similar to weekly but with more flexibility up to end date
            guard let activeDays = routine.activeDays, !activeDays.isEmpty else { return }
            
            for dayOffset in 0..<daysAhead {
                if let targetDate = calendar.date(byAdding: .day, value: dayOffset, to: today),
                   targetDate > lastGenerated,
                   targetDate <= generationEndDate {
                    let weekday = calendar.component(.weekday, from: targetDate)
                    // activeDays uses Apple Calendar convention: 1=Sun, 2=Mon, ..., 7=Sat
                    if activeDays.contains(weekday) {
                        datesToGenerate.append(targetDate)
                    }
                }
            }
        }
        
        // Create tasks for each date
        for targetDate in datesToGenerate {
            // Check if task already exists for this date
            let descriptor = FetchDescriptor<TaskWork>()
            let allTasks = (try? context.fetch(descriptor)) ?? []

            let existingTask = allTasks.first { task in
                task.routine?.id == routine.id &&
                task.scheduledDate != nil &&
                Calendar.current.isDate(task.scheduledDate!, inSameDayAs: targetDate)
            }

            if existingTask == nil {
                // Merge the routine's timeOfDay into the target date so
                // dueDate/scheduledDate carry the correct hour & minute
                // instead of defaulting to 00:00.
                let taskDate: Date
                if let timeOfDay = routine.timeOfDay {
                    let tc = calendar.dateComponents([.hour, .minute], from: timeOfDay)
                    taskDate = calendar.date(
                        bySettingHour: tc.hour ?? 9,
                        minute: tc.minute ?? 0,
                        second: 0,
                        of: targetDate
                    ) ?? targetDate
                } else {
                    taskDate = targetDate
                }

                // Create new task with the correct date+time
                let task = TaskWork(
                    title: routine.title,
                    detail: "Generated from routine",
                    createdAt: Date(),
                    dueDate: taskDate,
                    isRecurring: true,
                    generatedDate: Date(),
                    scheduledDate: taskDate
                )
                task.routine = routine
                context.insert(task)

                // Use the same merged date for the notification.
                let notificationDate = taskDate
                if notificationDate > Date() {
                    Task {
                        await NotificationManager.shared.scheduleTaskDueNotification(
                            taskId: task.id.uuidString,
                            taskTitle: routine.title,
                            dueDate: notificationDate
                        )
                    }
                }
            }
        }
        
        // Update last generated date
        routine.lastGeneratedDate = today
    }
    
    /// Update streak when a routine task is completed
    func updateStreakForRoutine(_ routine: Routine, completionDate: Date, context: ModelContext) {
        let calendar = Calendar.current
        let completionDay = calendar.startOfDay(for: completionDate)
        
        // Add completion date to array for consistency tracking
        routine.completionDates.append(completionDate)
        
        // Clean up old completion dates (keep only last 90 days for performance)
        let ninetyDaysAgo = calendar.date(byAdding: .day, value: -90, to: Date()) ?? Date()
        routine.completionDates = routine.completionDates.filter { $0 >= ninetyDaysAgo }
        
        if let lastCompleted = routine.lastCompletedDate {
            let lastCompletedDay = calendar.startOfDay(for: lastCompleted)
            let daysBetween = calendar.dateComponents([.day], from: lastCompletedDay, to: completionDay).day ?? 0
            
            if daysBetween == 1 {
                // Consecutive day - increment streak
                routine.currentStreak += 1
                if routine.currentStreak > routine.longestStreak {
                    routine.longestStreak = routine.currentStreak
                }
                
                // Trigger haptic feedback for streak milestones
                if routine.currentStreak % 7 == 0 {
                    // Weekly milestone - medium impact
                    DispatchQueue.main.async {
                        let generator = UIImpactFeedbackGenerator(style: .medium)
                        generator.impactOccurred()
                    }
                } else if routine.currentStreak >= 30 || routine.currentStreak % 30 == 0 {
                    // Monthly milestone - heavy impact
                    DispatchQueue.main.async {
                        let generator = UIImpactFeedbackGenerator(style: .heavy)
                        generator.impactOccurred()
                    }
                }
            } else if daysBetween > 1 {
                // Streak broken - reset to 1
                routine.currentStreak = 1
            }
            // Same day completion doesn't change streak
        } else {
            // First completion
            routine.currentStreak = 1
            routine.longestStreak = 1
        }
        
        routine.totalCompletions += 1
        routine.lastCompletedDate = completionDate

        // Record the check-in to PAI episodic memory so Lumina tracks habit progress.
        PAIMemoryBridge.shared.recordRoutineCheckin(routine)

        try? context.save()
    }
    
    /// Get upcoming routine tasks for display
    func getUpcomingRoutineTasks(context: ModelContext, days: Int = 7) -> [TaskWork] {
        let calendar = Calendar.current
        let today = calendar.startOfDay(for: Date())
        let endDate = calendar.date(byAdding: .day, value: days, to: today)!
        
        let descriptor = FetchDescriptor<TaskWork>(
            predicate: #Predicate { task in
                task.isRecurring &&
                task.scheduledDate != nil &&
                task.scheduledDate! >= today &&
                task.scheduledDate! <= endDate &&
                task.completedAt == nil
            },
            sortBy: [SortDescriptor(\.scheduledDate)]
        )
        
        return (try? context.fetch(descriptor)) ?? []
    }
}
