//
//  Routine.swift
//  iAlly
//
//  Created on 9/12/2025.
//

import Foundation
import SwiftData

@Model
final class Routine {
    var id: UUID = UUID()
    var title: String = ""
    var lifeDomain: LifeDomain = LifeDomain.personal
    var icon: String = "repeat.circle.fill"
    var colorHex: String = "#4C8BF5"
    var createdAt: Date = Date()
    
    // Recurrence settings
    var frequency: RecurrenceFrequency = RecurrenceFrequency.daily
    var activeDays: [Int]? // For weekly: Apple Calendar convention (1=Sun, 2=Mon, ..., 7=Sat). For monthly: day of month (1-31)
    var timeOfDay: Date? // Preferred time to do the routine
    var autoGenerateDays: Int = 7 // How many days in advance to generate tasks
    var startDate: Date? // Start date for routine (when it begins)
    var endDate: Date? // Optional end date for the routine
    
    // Advanced recurrence settings
    var weekInterval: Int? // Every N weeks (e.g., 2 = every 2 weeks)
    var monthInterval: Int? // Every N months (e.g., 3 = every 3 months)
    var monthWeek: Int? // Which week of month (1=first, 2=second, 3=third, 4=fourth, -1=last)
    var customIntervalDays: Int? // Every N days (e.g., 3 = every 3 days)
    var weekdaysOnly: Bool = false // Skip weekends for daily routines
    var exceptions: [Date] = [] // Specific dates to skip
    
    // Demo data flag
    var isDemo: Bool = false // True if this is demo data that can be removed
    
    // Instance modifications tracking
    var instanceModificationsData: Data? // JSON encoded [String: InstanceModification]
    
    // Status and tracking
    var isActive: Bool = true
    var currentStreak: Int = 0
    var longestStreak: Int = 0
    var totalCompletions: Int = 0
    var lastCompletedDate: Date?
    var lastGeneratedDate: Date?
    var completionDates: [Date] = [] // Track all completion dates for accurate consistency calculation
    
    // Growth Mindset resilience tracking
    var streakBreakCount: Int = 0 // Number of times streak was broken
    var recoveryCount: Int = 0 // Number of times routine was resumed after break
    var totalMissedDays: Int = 0 // Total days routine was supposed to happen but didn't
    
    // Relationships
    @Relationship(deleteRule: .nullify, inverse: \TaskWork.routine)
    var generatedTasks: [TaskWork]?
    
    var timeBlocks: [TimeBlock]? // Inverse relationship
    
    @Relationship(deleteRule: .cascade, inverse: \MindsetEvent.routine) var mindsetEvents: [MindsetEvent]?
    
    // Computed properties for instance modifications
    var instanceModifications: [String: InstanceModification] {
        get {
            guard let data = instanceModificationsData,
                  let decoded = try? JSONDecoder().decode([String: InstanceModification].self, from: data) else {
                return [:]
            }
            return decoded
        }
        set {
            instanceModificationsData = try? JSONEncoder().encode(newValue)
        }
    }
    
    // Computed properties
    var completionRate: Double {
        // For routines, show recent consistency (last 30 days)
        // This makes more sense than time-based % since routines have no end date
        let calendar = Calendar.current
        let thirtyDaysAgo = calendar.date(byAdding: .day, value: -30, to: Date()) ?? Date()
        let startDate = max(createdAt, thirtyDaysAgo)
        
        let daysSinceStart = calendar.dateComponents([.day], from: startDate, to: Date()).day ?? 0
        guard daysSinceStart > 0 else { return 0.0 }
        
        // Count actual completions in last 30 days
        let recentCompletions = completionDates.filter { $0 >= thirtyDaysAgo }.count
        
        // Calculate expected completions based on frequency
        let expectedCompletions: Double
        switch frequency {
        case .daily:
            expectedCompletions = Double(daysSinceStart)
        case .weekly:
            let weeks = Double(daysSinceStart) / 7.0
            expectedCompletions = weeks * Double(activeDays?.count ?? 1)
        case .monthly:
            expectedCompletions = Double(daysSinceStart) / 30.0
        case .custom:
            let weeks = Double(daysSinceStart) / 7.0
            expectedCompletions = weeks * Double(activeDays?.count ?? 1)
        }
        
        guard expectedCompletions > 0 else { return 0.0 }
        
        return min(Double(recentCompletions) / expectedCompletions, 1.0)
    }
    
    // Weekly consistency (last 7 days)
    var weeklyConsistency: Double {
        let calendar = Calendar.current
        let sevenDaysAgo = calendar.date(byAdding: .day, value: -7, to: Date()) ?? Date()
        let startDate = max(createdAt, sevenDaysAgo)
        
        let daysSinceStart = calendar.dateComponents([.day], from: startDate, to: Date()).day ?? 0
        guard daysSinceStart > 0 else { return 0.0 }
        
        let recentCompletions = completionDates.filter { $0 >= sevenDaysAgo }.count
        
        let expectedCompletions: Double
        switch frequency {
        case .daily:
            expectedCompletions = Double(daysSinceStart)
        case .weekly:
            expectedCompletions = Double(activeDays?.count ?? 1)
        case .monthly:
            expectedCompletions = 0.25 // Roughly 1 per month
        case .custom:
            expectedCompletions = Double(activeDays?.count ?? 1)
        }
        
        guard expectedCompletions > 0 else { return 0.0 }
        return min(Double(recentCompletions) / expectedCompletions, 1.0)
    }
    
    // Resilience metrics
    var recoveryRate: Double {
        guard streakBreakCount > 0 else { return 1.0 }
        return Double(recoveryCount) / Double(streakBreakCount)
    }
    
    var abandonmentRate: Double {
        guard streakBreakCount > 0 else { return 0.0 }
        let abandoned = streakBreakCount - recoveryCount
        return Double(abandoned) / Double(streakBreakCount)
    }
    
    init(
        id: UUID = UUID(),
        title: String,
        lifeDomain: LifeDomain,
        icon: String = "repeat.circle.fill",
        colorHex: String = "#4C8BF5",
        createdAt: Date = Date(),
        frequency: RecurrenceFrequency = .daily,
        activeDays: [Int]? = nil,
        timeOfDay: Date? = nil,
        autoGenerateDays: Int = 14,
        endDate: Date? = nil,
        isActive: Bool = true,
        currentStreak: Int = 0,
        longestStreak: Int = 0,
        totalCompletions: Int = 0,
        lastCompletedDate: Date? = nil,
        lastGeneratedDate: Date? = nil,
        completionDates: [Date] = []
    ) {
        self.id = id
        self.title = title
        self.lifeDomain = lifeDomain
        self.icon = icon
        self.colorHex = colorHex
        self.createdAt = createdAt
        self.frequency = frequency
        self.activeDays = activeDays
        self.timeOfDay = timeOfDay
        self.autoGenerateDays = autoGenerateDays
        self.endDate = endDate
        self.isActive = isActive
        self.currentStreak = currentStreak
        self.longestStreak = longestStreak
        self.totalCompletions = totalCompletions
        self.lastCompletedDate = lastCompletedDate
        self.lastGeneratedDate = lastGeneratedDate
        self.completionDates = completionDates
    }
}

enum RecurrenceFrequency: String, Codable, CaseIterable {
    case daily = "Daily"
    case weekly = "Weekly"
    case monthly = "Monthly"
    case custom = "Custom"
    
    var icon: String {
        switch self {
        case .daily: return "sun.max.fill"
        case .weekly: return "calendar.circle.fill"
        case .monthly: return "calendar"
        case .custom: return "slider.horizontal.3"
        }
    }
    
    var description: String {
        switch self {
        case .daily: return "Every day"
        case .weekly: return "Every week"
        case .monthly: return "Every month"
        case .custom: return "Custom schedule"
        }
    }
}

// MARK: - Instance Modification

/// Tracks modifications to individual recurring task instances
struct InstanceModification: Codable, Equatable {
    let instanceDate: Date        // Original scheduled date
    var newDate: Date?            // Rescheduled to this date (nil if skipped)
    var isSkipped: Bool           // True if this instance is skipped
    var reason: String?           // Optional note about why it was modified
    var modifiedAt: Date          // When the modification was made
    
    init(instanceDate: Date, newDate: Date? = nil, isSkipped: Bool = false, reason: String? = nil) {
        self.instanceDate = instanceDate
        self.newDate = newDate
        self.isSkipped = isSkipped
        self.reason = reason
        self.modifiedAt = Date()
    }
    
    var isRescheduled: Bool {
        newDate != nil && !isSkipped
    }
}
